/**
 * Prometheus Telemetry Metrics for MARL Market-Making Engine.
 *
 * Implements low-latency metric recorders tracking quoting activity,
 * fills, inventory skew, delta neutrality, and toxicity tripwires.
 *
 * @module desk/marl/telemetry/marl-metrics
 */

import { Counter, Gauge, Histogram } from 'prom-client';
import { register } from '../../../platform/middleware/prometheus-registry';

export const marlQuotesTotal = new Counter({
  name: 'marl_quotes_total',
  help: 'Total number of quotes generated by MARL agents',
  labelNames: ['agent_id', 'symbol', 'side', 'status'],
  registers: [register],
});

export const marlFillsTotal = new Counter({
  name: 'marl_fills_total',
  help: 'Total number of maker fills executed',
  labelNames: ['agent_id', 'symbol', 'side'],
  registers: [register],
});

export const marlInventorySkewGauge = new Gauge({
  name: 'marl_inventory_skew',
  help: 'Current inventory skew of the MARL market maker',
  labelNames: ['symbol'],
  registers: [register],
});

export const marlNetDeltaGauge = new Gauge({
  name: 'marl_net_delta',
  help: 'Current portfolio net delta across prediction CLOB and CEX venues',
  labelNames: ['symbol'],
  registers: [register],
});

export const marlRealizedPnlCounter = new Counter({
  name: 'marl_realized_pnl_usd',
  help: 'Cumulative realized PnL in USD from market making operations',
  labelNames: ['symbol', 'pnl_type'],
  registers: [register],
});

export const marlToxicityEventsTotal = new Counter({
  name: 'marl_toxicity_events_total',
  help: 'Total order flow toxicity tripwire activations',
  labelNames: ['symbol', 'reason'],
  registers: [register],
});

export const marlHedgeLatencyHistogram = new Histogram({
  name: 'marl_hedge_latency_ms',
  help: 'Execution latency of cross-venue delta hedges in milliseconds',
  labelNames: ['venue', 'status'],
  buckets: [5, 10, 25, 50, 100, 250, 500, 1000, 2500],
  registers: [register],
});

export class MarlMetricsRecorder {
  private quotesCount = 0;
  private fillsCount = 0;
  private totalFilledSize = 0;
  private currentInventory = 0;
  private currentNetDelta = 0;
  private realizedPnl = 0;
  private toxicityTripwireEvents = 0;
  private readonly hedgeLatencies: number[] = [];

  public recordQuote(
    action: 'posted' | 'canceled' | 'rejected',
    side: 'bid' | 'ask' | 'both',
    symbol = 'UNKNOWN',
    agentId = 'default',
  ): void {
    this.quotesCount += 1;
    marlQuotesTotal.inc({ agent_id: agentId, symbol, side, status: action });
  }

  public recordFill(
    side: 'bid' | 'ask',
    size: number,
    fillPrice: number,
    _spreadBps = 0,
    symbol = 'UNKNOWN',
    agentId = 'default',
  ): void {
    this.fillsCount += 1;
    this.totalFilledSize += size;
    marlFillsTotal.inc({ agent_id: agentId, symbol, side }, size);
  }

  public recordInventorySkew(inventory: number, notionalUsd: number, symbol = 'UNKNOWN'): void {
    this.currentInventory = inventory;
    marlInventorySkewGauge.set({ symbol }, inventory);
  }

  public recordNetDelta(netDelta: number, _polyDelta = 0, _cexDelta = 0, symbol = 'UNKNOWN'): void {
    this.currentNetDelta = netDelta;
    marlNetDeltaGauge.set({ symbol }, netDelta);
  }

  public recordPnl(realizedUsd: number, _unrealizedUsd = 0, symbol = 'UNKNOWN'): void {
    this.realizedPnl = realizedUsd;
    const pnlType = realizedUsd >= 0 ? 'profit' : 'loss';
    marlRealizedPnlCounter.inc({ symbol, pnl_type: pnlType }, Math.abs(realizedUsd));
  }

  public recordToxicity(
    vpin: number,
    kylesLambda: number,
    tripwireTripped: boolean,
    symbol = 'UNKNOWN',
    reason = 'vpin_spike',
  ): void {
    if (tripwireTripped) {
      this.toxicityTripwireEvents += 1;
      marlToxicityEventsTotal.inc({ symbol, reason });
    }
  }

  public recordHedgeLatency(venue: string, latencyMs: number, status = 'success'): void {
    this.hedgeLatencies.push(latencyMs);
    marlHedgeLatencyHistogram.observe({ venue, status }, latencyMs);
  }

  public getSnapshot(): {
    quotesCount: number;
    fillsCount: number;
    fillRate: number;
    inventory: number;
    netDelta: number;
    realizedPnl: number;
    toxicityTripwireEvents: number;
  } {
    return {
      quotesCount: this.quotesCount,
      fillsCount: this.fillsCount,
      fillRate: this.quotesCount > 0 ? this.fillsCount / this.quotesCount : 0,
      inventory: this.currentInventory,
      netDelta: this.currentNetDelta,
      realizedPnl: this.realizedPnl,
      toxicityTripwireEvents: this.toxicityTripwireEvents,
    };
  }
}
