/**
 * Commission Calculator
 * Calculates referral commissions based on revenue
 */

import { } from './referral-repository';

export class CommissionCalculator {
  private readonly DEFAULT_COMMISSION_RATE = 0.10; // 10%

  /**
   * Calculate commission for a conversion
   * @param revenue - The revenue generated by the referred tenant
   * @returns Commission amount
   */
  calculateCommission(revenue: number): number {
    if (revenue <= 0) return 0;
    return revenue * this.DEFAULT_COMMISSION_RATE;
  }

  /**
   * Calculate commission with custom rate
   * @param revenue - The revenue generated
   * @param rate - Commission rate (e.g., 0.10 for 10%)
   * @returns Commission amount
   */
  calculateCommissionWithRate(revenue: number, rate: number): number {
    if (revenue <= 0 || rate <= 0) return 0;
    return revenue * rate;
  }

  /**
   * Calculate period for monthly payouts
   * Returns the previous calendar month
   */
  getPreviousMonthPeriod(): { start: Date; end: Date } {
    const now = new Date();
    const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();
    const month = now.getMonth() === 0 ? 11 : now.getMonth() - 1;

    const start = new Date(year, month, 1);
    const end = new Date(year, month + 1, 0); // last day of month

    return { start, end };
  }

  /**
   * Calculate current month period
   */
  getCurrentMonthPeriod(): { start: Date; end: Date } {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    return { start, end };
  }
}

export const commissionCalculator = new CommissionCalculator();
