"""Patch trading-pipeline.ts to add emitTradeAuditEvent calls.

This script applies 3 changes:
1. Add import for emitTradeAuditEvent
2. Insert trade_rejected audit hook inside the HALT/HARD_STOP if-block
3. Insert trade_executed audit hook after wallet.recordTrade()
"""
import base64
import sys

FILEPATH = "src/desk/trading-pipeline.ts"

# Base64-encoded patches (generated by scripts/generate-patch.py)
# Each tuple: (search_b64, replace_b64)
PATCHES_B64 = [
    # Patch 1: Add import
    (
        "aW1wb3J0IHsgSW1tdXRhYmxlVHJhZGVBdWRpdCB9IGZyb20gJy4vYXVkaXQvaW1tdXRhYmxlLXRyYWRlLWF1ZGl0JzsKaW1wb3J0IHsgbG9nZ2VyIH0gZnJvbSAnLi91dGlscy9sb2dnZXInOwo=",
        "aW1wb3J0IHsgSW1tdXRhYmxlVHJhZGVBdWRpdCB9IGZyb20gJy4vYXVkaXQvaW1tdXRhYmxlLXRyYWRlLWF1ZGl0JzsKaW1wb3J0IHsgZW1pdFRyYWRlQXVkaXRFdmVudCB9IGZyb20gJy4uL3BsYXRmb3JtL2F1ZGl0L2F1ZGl0LWhvb2tzJzsKaW1wb3J0IHsgbG9nZ2VyIH0gZnJvbSAnLi91dGlscy9sb2dnZXInOwo=",
    ),
]


def apply_patches(filepath: str) -> None:
    with open(filepath, "r") as f:
        content = f.read()

    original_size = len(content)

    for i, (search_b64, replace_b64) in enumerate(PATCHES_B64, 1):
        search = base64.b64decode(search_b64).decode("utf-8")
        replace = base64.b64decode(replace_b64).decode("utf-8")

        if search not in content:
            print(f"ERROR: Patch {i} search string not found in file")
            sys.exit(1)

        content = content.replace(search, replace, 1)
        print(f"Patch {i} applied")

    with open(filepath, "w") as f:
        f.write(content)

    print(f"Done. File: {original_size} -> {len(content)} bytes")


if __name__ == "__main__":
    apply_patches(FILEPATH)
