/**
 * Baseline Runner
 *
 * Runs all baseline strategies on a dataset and produces evaluation reports.
 * Wraps baseline strategies with computeMetrics so they compare apples-to-apples
 * against candidate strategies.
 */

import { computeMetrics } from '../../desk/backtesting/metrics-calculator';
import type { CandleLike } from '../regimes/regime-types';
import { buyAndHold } from './baseline-strategies';
import { randomEntry } from './baseline-strategies';
import { simpleMomentum } from './baseline-strategies';
import { simpleMeanReversion } from './baseline-strategies';

/** Result of a baseline run with metrics attached. */
export interface BaselineRun {
  name: string;
  /** Trades generated by this baseline. */
  trades: { timestamp: string; equity: number }[];
  report: ReturnType<typeof computeMetrics>;
}

/**
 * Run all four baselines on a candle dataset.
 *
 * Returns reports that can be compared against experiment results.
 */
export function runAllBaselines(
  candles: CandleLike[],
  costFeeBps = 5,
  costSlippageBps = 2,
  seed = 42,
): BaselineRun[] {
  const closes = candles.map((c) => ({ timestamp: c.timestamp, close: c.close }));

  const strategies = [
    buyAndHold(closes, { cost: { feeBps: costFeeBps, slippageBps: costSlippageBps }, seed }),
    randomEntry(closes, { cost: { feeBps: costFeeBps, slippageBps: costSlippageBps }, seed }),
    simpleMomentum(closes, { cost: { feeBps: costFeeBps, slippageBps: costSlippageBps }, seed }),
    simpleMeanReversion(closes, { cost: { feeBps: costFeeBps, slippageBps: costSlippageBps }, seed }),
  ];

  return strategies.map((result) => {
    // Build equity curve from cumulative trade PnL so Sharpe/drawdown
    // reflect strategy returns, not the raw price series.
    const equity = buildEquityCurve(result.trades, closes);
    return {
      name: result.name,
      trades: equity,
      report: computeMetrics(result.trades, equity),
    };
  });
}

/**
 * Build a cumulative equity curve from trade PnL values.
 *
 * Uses the raw close price as baseline (starting equity = first close),
    then accumulates trade PnL on top. This gives each baseline a distinct
    equity curve for Sharpe/maxDrawdown computation.
 */
function buildEquityCurve(
  trades: BacktestTrade[],
  closes: Array<{ timestamp: string; close: number }>,
): Array<{ timestamp: string; equity: number }> {
  if (closes.length === 0) return [];
  const baseline = closes.map((c) => ({ timestamp: c.timestamp, equity: c.close }));
  if (trades.length === 0) return baseline;

  // Map trade entry timestamps to their PnL, then accumulate.
  const pnlByTimestamp = new Map<number, number>();
  for (const t of trades) {
    const ts = new Date(t.timestamp).getTime();
    pnlByTimestamp.set(ts, (pnlByTimestamp.get(ts) ?? 0) + t.pnl);
  }

  let runningPnl = 0;
  for (const bar of baseline) {
    const ts = new Date(bar.timestamp).getTime();
    runningPnl += pnlByTimestamp.get(ts) ?? 0;
    bar.equity += runningPnl;
  }
  return baseline;
}